title:            Sunil Anthony
description:      My developer blogs
url:              http://sunilanthony.github.io # Site url. Place your path here, or leave blank to work local.
logo:             sasa-jekyll-theme-logo.png # Replace for your own logo.
signoff:          sunilanthony # Your name.
disqus_shortname: sunilanthony-com # disqus comments, create your account on disqus site and place your id here.
facebook_appid:   # appid for like button, do the same above.
google_analytics: # Place your ID here.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Projects
    url:          /projects
  - name:         Contact
    url:          mailto:sunilanthony17@gmail.com
    external:     true

social-links:
  - name:         GitHub
    url:          http://github.com/sunilanthony
    icon:         icon-github
    external:     true
  - name:         Linkedin
    url:          https://www.linkedin.com/in/sunil-anthony-80765b11/
    icon:         icon-linkedin
    external:     true
  - name:         Twitter
    url:          https://twitter.com/zXSwordXz
    icon:         icon-twitter
    external:     true
pygments:         false
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart